// Fixed texts of the student view, in the language of the worksheet.
import type { Lang } from '../model/types';

const de = {
  loading: 'Der Auftrag wird geladen …',
  notFound: 'Diesen Auftrag gibt es nicht (mehr). Ist der Link vollständig?',
  offline: 'Keine Verbindung. Prüfe das Internet und lade die Seite neu.',
  practice: 'Übung',
  test: 'Test',
  yourName: 'Dein Name',
  namePlaceholder: 'z. B. Lea M.',
  nameHint: 'Vorname und der erste Buchstabe des Nachnamens',
  nameBad: 'Bitte Vorname und den ersten Buchstaben des Nachnamens, z. B. „Lea M.“',
  start: 'Los geht’s',
  check: 'Prüfen',
  showSolution: 'Lösung zeigen',
  sample: 'Musterlösung zeigen',
  right: (r: number, t: number) => (r === t ? 'Alles richtig!' : `${r} von ${t} richtig`),
  handIn: 'Abgeben',
  handInAsk: 'Jetzt abgeben? Danach kannst du nichts mehr ändern.',
  handedIn: 'Abgegeben',
  handedInText: 'Deine Lehrkraft sieht jetzt deine Antworten. Du kannst die Seite schließen.',
  result: (r: number, t: number) => `Du hast ${r} von ${t} richtig.`,
  saved: 'gespeichert',
  sending: 'wird gesendet …',
  notSent: 'noch nicht gesendet – kein Internet?',
  paper: 'Diese Aufgabe bitte auf Papier bearbeiten.',
  order: 'Tippe die Teile in der richtigen Reihenfolge an.',
  reset: 'Neu',
  choose: 'wählen …',
  write: 'Hier schreiben …',
  progress: (d: number, n: number) => `${d} von ${n} Aufgaben bearbeitet`,
  privacy: 'Deine Antworten werden verschlüsselt gesendet; nur deine Lehrkraft kann sie lesen. Nach 14 Tagen werden sie vom Server gelöscht.',
  tf: { T: 'richtig', F: 'falsch', NG: 'steht nicht im Text' } as Record<string, string>,
  solution: 'Lösung',
};

const en: typeof de = {
  loading: 'Loading the task …',
  notFound: 'This task does not exist (any more). Is the link complete?',
  offline: 'No connection. Check the internet and reload the page.',
  practice: 'Practice',
  test: 'Test',
  yourName: 'Your name',
  namePlaceholder: 'e.g. Lea M.',
  nameHint: 'First name and the first letter of your surname',
  nameBad: 'Please write your first name and the first letter of your surname, e.g. “Lea M.”',
  start: 'Let’s go',
  check: 'Check',
  showSolution: 'Show solution',
  sample: 'Show model answer',
  right: (r: number, t: number) => (r === t ? 'All correct!' : `${r} of ${t} correct`),
  handIn: 'Hand in',
  handInAsk: 'Hand in now? You cannot change anything afterwards.',
  handedIn: 'Handed in',
  handedInText: 'Your teacher can see your answers now. You can close this page.',
  result: (r: number, t: number) => `You got ${r} of ${t} right.`,
  saved: 'saved',
  sending: 'sending …',
  notSent: 'not sent yet – no internet?',
  paper: 'Please do this task on paper.',
  order: 'Tap the parts in the right order.',
  reset: 'Reset',
  choose: 'choose …',
  write: 'Write here …',
  progress: (d: number, n: number) => `${d} of ${n} tasks done`,
  privacy: 'Your answers are sent encrypted; only your teacher can read them. They are deleted from the server after 14 days.',
  tf: { T: 'true', F: 'false', NG: 'not in the text' },
  solution: 'Solution',
};

export const STUDENT_TEXT: Record<Lang, typeof de> = { de, en };
export type StudentText = typeof de;
