import {
  BadgeHelp,
  BookA,
  BookMarked,
  BookOpenText,
  Calculator,
  CheckCheck,
  Columns3,
  Contact,
  FoldHorizontal,
  Grid3x3,
  Headphones,
  Images,
  Languages,
  MessagesSquare,
  Network,
  PenLine,
  Repeat2,
  Shuffle,
  Table2,
  AlignLeft,
  CalendarClock,
  ClipboardCheck,
  MessageCircleQuestion,
  Target,
  ArrowLeftRight,
  Brush,
  Heading,
  Image,
  Info,
  Lightbulb,
  ListChecks,
  PencilLine,
  QrCode,
  SmilePlus,
  Table,
  Tag,
  TextCursorInput,
  Workflow,
  type LucideIcon,
} from 'lucide-react';
import type { BlockType } from './model/types';

export const BLOCK_ICONS: Record<BlockType, LucideIcon> = {
  heading: Heading,
  text: AlignLeft,
  hint: Info,
  merksatz: Lightbulb,
  wordbank: Tag,
  image: Image,
  flow: Workflow,
  qr: QrCode,
  open: PencilLine,
  mc: ListChecks,
  gap: TextCursorInput,
  table: Table,
  match: ArrowLeftRight,
  draw: Brush,
  selfcheck: SmilePlus,
  plan: CalendarClock,
  goal: Target,
  expect: ClipboardCheck,
  recall: MessageCircleQuestion,
  vocab: BookA,
  foldtest: FoldHorizontal,
  picvocab: Images,
  wordweb: Network,
  grammar: BookMarked,
  forms: Table2,
  jumble: Shuffle,
  transform: Repeat2,
  syntax: Columns3,
  listening: Headphones,
  reading: BookOpenText,
  truefalse: CheckCheck,
  phrases: MessagesSquare,
  rolecards: Contact,
  bingo: Grid3x3,
  writing: PenLine,
  mediation: Languages,
  gradescale: Calculator,
  tipcards: BadgeHelp,
};

/** Lucide icon in the design system's style: stroke 2.75, round caps and joins. */
export function Icon({ icon: I, size = 16 }: { icon: LucideIcon; size?: number }) {
  return <I size={size} strokeWidth={2.75} aria-hidden="true" focusable="false" style={{ display: 'block', flex: 'none' }} />;
}
