// Topic icons for the header band (Kopfband): one icon per overarching topic, the same on every page.
// A curated set in groups, so the bundle does not carry all of Lucide and the picker stays easy to scan.
// Keys are Lucide's kebab-case names ("home" is Lucide's alias for House); stored documents refer to them, so keys never change.
import {
  Accessibility,
  AlarmClock,
  Amphora,
  Anchor,
  Apple,
  Atom,
  Baby,
  Backpack,
  BatteryCharging,
  Bed,
  Bike,
  Binary,
  Biohazard,
  Bird,
  Bone,
  BookA,
  BookOpen,
  Bot,
  Brain,
  Briefcase,
  BriefcaseMedical,
  Brush,
  Bug,
  Building,
  Building2,
  Bus,
  Cake,
  Calculator,
  Calendar,
  Camera,
  CandyCane,
  Car,
  Carrot,
  Castle,
  Cat,
  ChartColumn,
  ChartPie,
  Church,
  CircuitBoard,
  Clapperboard,
  ClipboardList,
  Clock,
  CloudLightning,
  CloudRain,
  CloudSunRain,
  Code,
  Coffee,
  Cog,
  Coins,
  Compass,
  Construction,
  Container,
  Cookie,
  Cpu,
  Croissant,
  Crown,
  CupSoda,
  Divide,
  Dna,
  Dog,
  Drama,
  Drill,
  Droplets,
  Drum,
  Dumbbell,
  Ear,
  Earth,
  Egg,
  Euro,
  Eye,
  Factory,
  Feather,
  Film,
  Fish,
  Flag,
  Flame,
  FlaskConical,
  FlaskRound,
  Flower2,
  Footprints,
  Fuel,
  Gamepad2,
  Gauge,
  Gavel,
  Ghost,
  Gift,
  Glasses,
  Globe,
  Goal,
  GraduationCap,
  Guitar,
  Hammer,
  Hand,
  HandCoins,
  HandHeart,
  Handshake,
  HardHat,
  Headphones,
  Heart,
  HeartHandshake,
  HeartPulse,
  Hospital,
  Hotel,
  Hourglass,
  House,
  IceCreamCone,
  Key,
  Landmark,
  Languages,
  Laptop,
  Leaf,
  Library,
  Lightbulb,
  ListChecks,
  Lock,
  Magnet,
  Mail,
  Map as MapIcon,
  MapPin,
  Medal,
  Megaphone,
  MessageCircle,
  MessagesSquare,
  Mic,
  Microscope,
  MicVocal,
  Milk,
  Moon,
  Mountain,
  MountainSnow,
  Music,
  Newspaper,
  NotebookPen,
  Orbit,
  Palette,
  PartyPopper,
  PawPrint,
  Pencil,
  PencilRuler,
  PenLine,
  Percent,
  Pi,
  Piano,
  Pickaxe,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Plug,
  Popcorn,
  Presentation,
  Puzzle,
  Pyramid,
  Quote,
  Rabbit,
  Rainbow,
  Rat,
  Recycle,
  Rocket,
  Route,
  Ruler,
  Sailboat,
  Salad,
  Sandwich,
  Satellite,
  Scale,
  School,
  Scissors,
  Scroll,
  Search,
  Shapes,
  Shell,
  Shield,
  ShieldCheck,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Shrimp,
  Sigma,
  Signpost,
  Siren,
  Smartphone,
  Smile,
  Snail,
  Snowflake,
  Sofa,
  SolarPanel,
  Sparkles,
  Speech,
  SpellCheck,
  Sprout,
  Squirrel,
  Star,
  Stethoscope,
  Store,
  Sun,
  Sunrise,
  Sword,
  Swords,
  Syringe,
  Target,
  Telescope,
  Tent,
  TestTubes,
  Thermometer,
  ThermometerSun,
  Tickets,
  Tornado,
  Tractor,
  Train,
  TreeDeciduous,
  TreePalm,
  TreePine,
  Trees,
  Trophy,
  Truck,
  Turtle,
  Tv,
  Type,
  Umbrella,
  Users,
  Utensils,
  Volleyball,
  Vote,
  Waves,
  Weight,
  Wheat,
  Wind,
  Worm,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

export interface TopicIcon {
  key: string;
  icon: LucideIcon;
  /** German name, shown as tooltip and matched by the search field. */
  label: string;
  /** Extra German search words. */
  words?: string;
}

export interface TopicGroup {
  label: string;
  icons: TopicIcon[];
}

export const DEFAULT_TOPIC_ICON = 'thermometer-sun';

export const TOPIC_GROUPS: TopicGroup[] = [
  {
    label: 'Klima, Wetter und Erde',
    icons: [
      { key: 'thermometer-sun', icon: ThermometerSun, label: 'Klima', words: 'temperatur treibhaus wärme' },
      { key: 'sun', icon: Sun, label: 'Sonne', words: 'energie licht' },
      { key: 'cloud-sun-rain', icon: CloudSunRain, label: 'Wetter' },
      { key: 'cloud-rain', icon: CloudRain, label: 'Niederschlag', words: 'regen wasserkreislauf' },
      { key: 'cloud-lightning', icon: CloudLightning, label: 'Gewitter', words: 'blitz unwetter' },
      { key: 'tornado', icon: Tornado, label: 'Sturm', words: 'wirbelsturm hurrikan unwetter' },
      { key: 'rainbow', icon: Rainbow, label: 'Regenbogen', words: 'licht farben wetter' },
      { key: 'sunrise', icon: Sunrise, label: 'Tageszeiten', words: 'sonnenaufgang morgen' },
      { key: 'umbrella', icon: Umbrella, label: 'Regen', words: 'wetter schirm' },
      { key: 'wind', icon: Wind, label: 'Wind', words: 'luft atmosphäre' },
      { key: 'snowflake', icon: Snowflake, label: 'Eis', words: 'schnee kälte gletscher polar' },
      { key: 'earth', icon: Earth, label: 'Erde', words: 'planet welt' },
      { key: 'globe', icon: Globe, label: 'Globus', words: 'welt länder' },
      { key: 'map', icon: MapIcon, label: 'Karte', words: 'atlas geographie' },
      { key: 'compass', icon: Compass, label: 'Kompass', words: 'orientierung himmelsrichtung' },
      { key: 'map-pin', icon: MapPin, label: 'Ort', words: 'lage standort' },
      { key: 'signpost', icon: Signpost, label: 'Wegweiser', words: 'orientierung richtung' },
      { key: 'route', icon: Route, label: 'Route', words: 'weg reise karte' },
      { key: 'mountain', icon: Mountain, label: 'Gebirge', words: 'berg alpen relief vulkan' },
      { key: 'mountain-snow', icon: MountainSnow, label: 'Hochgebirge', words: 'alpen gletscher berge' },
      { key: 'waves', icon: Waves, label: 'Meer', words: 'ozean küste wasser' },
      { key: 'droplets', icon: Droplets, label: 'Wasser', words: 'fluss trinkwasser' },
      { key: 'shell', icon: Shell, label: 'Küste', words: 'strand muschel meer' },
      { key: 'pickaxe', icon: Pickaxe, label: 'Rohstoffe', words: 'bergbau gestein' },
      { key: 'tree-palm', icon: TreePalm, label: 'Tropen', words: 'palme regenwald urlaub' },
      { key: 'trees', icon: Trees, label: 'Wald', words: 'bäume regenwald ökosystem' },
    ],
  },
  {
    label: 'Natur und Tiere',
    icons: [
      { key: 'leaf', icon: Leaf, label: 'Pflanzen', words: 'biologie blatt' },
      { key: 'sprout', icon: Sprout, label: 'Wachstum', words: 'keimung samen' },
      { key: 'tree-pine', icon: TreePine, label: 'Wald', words: 'baum ökosystem' },
      { key: 'tree-deciduous', icon: TreeDeciduous, label: 'Laubbaum', words: 'baum jahreszeiten' },
      { key: 'flower-2', icon: Flower2, label: 'Blüte', words: 'blume bestäubung' },
      { key: 'bug', icon: Bug, label: 'Insekten', words: 'käfer tiere' },
      { key: 'fish', icon: Fish, label: 'Fische', words: 'tiere wasser' },
      { key: 'bird', icon: Bird, label: 'Vögel', words: 'tiere' },
      { key: 'paw-print', icon: PawPrint, label: 'Tiere', words: 'säugetiere zoologie' },
      { key: 'cat', icon: Cat, label: 'Katze', words: 'tiere haustier' },
      { key: 'rabbit', icon: Rabbit, label: 'Kaninchen', words: 'tiere haustier hase' },
      { key: 'squirrel', icon: Squirrel, label: 'Eichhörnchen', words: 'tiere wald' },
      { key: 'turtle', icon: Turtle, label: 'Schildkröte', words: 'reptilien tiere' },
      { key: 'snail', icon: Snail, label: 'Schnecke', words: 'tiere garten' },
      { key: 'rat', icon: Rat, label: 'Nagetiere', words: 'maus ratte tiere' },
      { key: 'shrimp', icon: Shrimp, label: 'Meerestiere', words: 'krebstiere tiere' },
      { key: 'worm', icon: Worm, label: 'Boden', words: 'regenwurm erde' },
      { key: 'feather', icon: Feather, label: 'Feder', words: 'vögel leicht' },
      { key: 'egg', icon: Egg, label: 'Ei', words: 'fortpflanzung ostern frühstück' },
      { key: 'dna', icon: Dna, label: 'Genetik', words: 'vererbung zelle' },
      { key: 'microscope', icon: Microscope, label: 'Mikroskop', words: 'zelle untersuchen' },
    ],
  },
  {
    label: 'Körper, Gesundheit und Ernährung',
    icons: [
      { key: 'heart-pulse', icon: HeartPulse, label: 'Körper', words: 'herz kreislauf gesundheit' },
      { key: 'brain', icon: Brain, label: 'Gehirn', words: 'nerven lernen' },
      { key: 'stethoscope', icon: Stethoscope, label: 'Gesundheit', words: 'medizin krankheit' },
      { key: 'bone', icon: Bone, label: 'Skelett', words: 'knochen körper' },
      { key: 'ear', icon: Ear, label: 'Hören', words: 'ohr sinne' },
      { key: 'eye', icon: Eye, label: 'Sehen', words: 'auge sinne' },
      { key: 'hand', icon: Hand, label: 'Hand', words: 'tastsinn körper' },
      { key: 'footprints', icon: Footprints, label: 'Spuren', words: 'bewegung evolution fußabdruck' },
      { key: 'baby', icon: Baby, label: 'Entwicklung', words: 'baby pubertät wachstum' },
      { key: 'pill', icon: Pill, label: 'Medikamente', words: 'sucht gesundheit' },
      { key: 'syringe', icon: Syringe, label: 'Impfen', words: 'medizin gesundheit' },
      { key: 'hospital', icon: Hospital, label: 'Krankenhaus', words: 'medizin notfall' },
      { key: 'biohazard', icon: Biohazard, label: 'Krankheitserreger', words: 'bakterien viren infektion' },
      { key: 'apple', icon: Apple, label: 'Ernährung', words: 'essen obst' },
      { key: 'salad', icon: Salad, label: 'Lebensmittel', words: 'essen kochen' },
      { key: 'wheat', icon: Wheat, label: 'Landwirtschaft', words: 'getreide ernte' },
      { key: 'carrot', icon: Carrot, label: 'Gemüse', words: 'ernährung gesund' },
      { key: 'milk', icon: Milk, label: 'Milch', words: 'ernährung frühstück' },
      { key: 'cookie', icon: Cookie, label: 'Süßes', words: 'zucker ernährung' },
      { key: 'cup-soda', icon: CupSoda, label: 'Getränke', words: 'zucker limo ernährung' },
      { key: 'recycle', icon: Recycle, label: 'Umwelt', words: 'nachhaltigkeit müll recycling' },
    ],
  },
  {
    label: 'Physik, Chemie und Technik',
    icons: [
      { key: 'atom', icon: Atom, label: 'Physik', words: 'teilchen' },
      { key: 'flask-conical', icon: FlaskConical, label: 'Chemie', words: 'versuch labor' },
      { key: 'flask-round', icon: FlaskRound, label: 'Chemie', words: 'kolben labor' },
      { key: 'test-tubes', icon: TestTubes, label: 'Experiment', words: 'reagenzglas labor' },
      { key: 'magnet', icon: Magnet, label: 'Magnetismus' },
      { key: 'zap', icon: Zap, label: 'Elektrizität', words: 'strom energie' },
      { key: 'flame', icon: Flame, label: 'Feuer', words: 'verbrennung wärme' },
      { key: 'lightbulb', icon: Lightbulb, label: 'Idee', words: 'licht erfindung' },
      { key: 'plug', icon: Plug, label: 'Stromkreis', words: 'strom elektrizität' },
      { key: 'battery-charging', icon: BatteryCharging, label: 'Batterie', words: 'akku energie strom' },
      { key: 'solar-panel', icon: SolarPanel, label: 'Solarenergie', words: 'erneuerbar energie sonne' },
      { key: 'fuel', icon: Fuel, label: 'Brennstoff', words: 'öl benzin energie' },
      { key: 'gauge', icon: Gauge, label: 'Messen', words: 'messgerät druck' },
      { key: 'thermometer', icon: Thermometer, label: 'Temperatur', words: 'wärme messen' },
      { key: 'weight', icon: Weight, label: 'Masse', words: 'gewicht wiegen' },
      { key: 'rocket', icon: Rocket, label: 'Raumfahrt', words: 'weltall' },
      { key: 'telescope', icon: Telescope, label: 'Astronomie', words: 'sterne weltall' },
      { key: 'moon', icon: Moon, label: 'Mond', words: 'nacht weltall' },
      { key: 'orbit', icon: Orbit, label: 'Planeten', words: 'sonnensystem weltall' },
      { key: 'satellite', icon: Satellite, label: 'Satellit', words: 'weltall kommunikation' },
      { key: 'cog', icon: Cog, label: 'Maschine', words: 'zahnrad technik' },
      { key: 'wrench', icon: Wrench, label: 'Werkzeug', words: 'reparieren technik' },
      { key: 'hammer', icon: Hammer, label: 'Werken', words: 'bauen holz' },
      { key: 'drill', icon: Drill, label: 'Bohrmaschine', words: 'werken technik' },
      { key: 'construction', icon: Construction, label: 'Baustelle', words: 'bauen verkehr' },
      { key: 'hard-hat', icon: HardHat, label: 'Arbeitssicherheit', words: 'beruf bauen' },
      { key: 'factory', icon: Factory, label: 'Industrie', words: 'fabrik wirtschaft' },
      { key: 'tractor', icon: Tractor, label: 'Traktor', words: 'landwirtschaft' },
      { key: 'car', icon: Car, label: 'Auto', words: 'verkehr mobilität' },
      { key: 'train', icon: Train, label: 'Verkehr', words: 'bahn mobilität' },
      { key: 'ship', icon: Ship, label: 'Handel', words: 'schiff hafen' },
      { key: 'sailboat', icon: Sailboat, label: 'Segeln', words: 'boot meer' },
      { key: 'plane', icon: Plane, label: 'Reisen', words: 'flugzeug tourismus' },
      { key: 'anchor', icon: Anchor, label: 'Hafen', words: 'seefahrt' },
      { key: 'truck', icon: Truck, label: 'Transport', words: 'lkw handel güter' },
    ],
  },
  {
    label: 'Mathematik und Informatik',
    icons: [
      { key: 'calculator', icon: Calculator, label: 'Rechnen', words: 'mathe' },
      { key: 'sigma', icon: Sigma, label: 'Mathematik', words: 'summe formel' },
      { key: 'pi', icon: Pi, label: 'Kreis', words: 'pi geometrie' },
      { key: 'percent', icon: Percent, label: 'Prozent', words: 'prozentrechnung zinsen' },
      { key: 'divide', icon: Divide, label: 'Bruchrechnung', words: 'teilen brüche' },
      { key: 'ruler', icon: Ruler, label: 'Messen', words: 'geometrie länge' },
      { key: 'pencil-ruler', icon: PencilRuler, label: 'Konstruieren', words: 'geometrie zeichnen' },
      { key: 'shapes', icon: Shapes, label: 'Geometrie', words: 'formen körper' },
      { key: 'chart-column', icon: ChartColumn, label: 'Diagramm', words: 'statistik daten' },
      { key: 'chart-pie', icon: ChartPie, label: 'Anteile', words: 'prozent bruch statistik' },
      { key: 'laptop', icon: Laptop, label: 'Computer', words: 'informatik medien' },
      { key: 'code', icon: Code, label: 'Programmieren', words: 'informatik' },
      { key: 'cpu', icon: Cpu, label: 'Computer', words: 'prozessor informatik' },
      { key: 'circuit-board', icon: CircuitBoard, label: 'Elektronik', words: 'platine technik' },
      { key: 'binary', icon: Binary, label: 'Daten', words: 'binär informatik codierung' },
      { key: 'bot', icon: Bot, label: 'Roboter', words: 'ki künstliche intelligenz' },
    ],
  },
  {
    label: 'Gesellschaft, Geschichte und Wirtschaft',
    icons: [
      { key: 'landmark', icon: Landmark, label: 'Staat', words: 'politik demokratie antike landeskunde sehenswürdigkeit london' },
      { key: 'vote', icon: Vote, label: 'Wahlen', words: 'politik demokratie' },
      { key: 'scale', icon: Scale, label: 'Recht', words: 'gerechtigkeit gesetz' },
      { key: 'gavel', icon: Gavel, label: 'Recht', words: 'gericht gesetz' },
      { key: 'users', icon: Users, label: 'Gesellschaft', words: 'gemeinschaft gruppe' },
      { key: 'handshake', icon: Handshake, label: 'Zusammenarbeit', words: 'frieden vertrag' },
      { key: 'heart-handshake', icon: HeartHandshake, label: 'Soziales', words: 'ehrenamt zusammenhalt' },
      { key: 'hand-heart', icon: HandHeart, label: 'Helfen', words: 'spende hilfe' },
      { key: 'accessibility', icon: Accessibility, label: 'Inklusion', words: 'barrierefrei teilhabe' },
      { key: 'coins', icon: Coins, label: 'Wirtschaft', words: 'geld finanzen' },
      { key: 'euro', icon: Euro, label: 'Geld', words: 'euro wirtschaft preise' },
      { key: 'piggy-bank', icon: PiggyBank, label: 'Sparen', words: 'geld taschengeld' },
      { key: 'hand-coins', icon: HandCoins, label: 'Taschengeld', words: 'geld bezahlen' },
      { key: 'shopping-bag', icon: ShoppingBag, label: 'Konsum', words: 'einkaufen werbung' },
      { key: 'store', icon: Store, label: 'Laden', words: 'markt geschäft' },
      { key: 'container', icon: Container, label: 'Welthandel', words: 'globalisierung hafen' },
      { key: 'briefcase', icon: Briefcase, label: 'Beruf', words: 'arbeit berufsorientierung' },
      { key: 'building-2', icon: Building2, label: 'Stadt', words: 'urbanisierung' },
      { key: 'building', icon: Building, label: 'Gebäude', words: 'wohnen stadt' },
      { key: 'hotel', icon: Hotel, label: 'Tourismus', words: 'hotel reisen' },
      { key: 'hourglass', icon: Hourglass, label: 'Zeit', words: 'geschichte epoche' },
      { key: 'scroll', icon: Scroll, label: 'Quellen', words: 'geschichte urkunde' },
      { key: 'pyramid', icon: Pyramid, label: 'Ägypten', words: 'antike hochkultur' },
      { key: 'amphora', icon: Amphora, label: 'Antike', words: 'griechen römer' },
      { key: 'castle', icon: Castle, label: 'Mittelalter', words: 'burg geschichte' },
      { key: 'crown', icon: Crown, label: 'Herrschaft', words: 'könig absolutismus' },
      { key: 'sword', icon: Sword, label: 'Konflikt', words: 'krieg geschichte' },
      { key: 'swords', icon: Swords, label: 'Ritter', words: 'kampf mittelalter' },
      { key: 'shield', icon: Shield, label: 'Schutz', words: 'wappen sicherheit' },
      { key: 'church', icon: Church, label: 'Religion', words: 'glaube ethik kirche' },
      { key: 'newspaper', icon: Newspaper, label: 'Medien', words: 'zeitung nachrichten' },
      { key: 'megaphone', icon: Megaphone, label: 'Werbung', words: 'protest meinung' },
    ],
  },
  {
    label: 'Sprachen und Kommunikation',
    icons: [
      { key: 'book-open', icon: BookOpen, label: 'Lesen', words: 'deutsch literatur buch' },
      { key: 'book-a', icon: BookA, label: 'Wörterbuch', words: 'vokabeln nachschlagen' },
      { key: 'library', icon: Library, label: 'Bibliothek', words: 'bücher lesen' },
      { key: 'notebook-pen', icon: NotebookPen, label: 'Lernjournal', words: 'heft notizen' },
      { key: 'pen-line', icon: PenLine, label: 'Schreiben', words: 'deutsch aufsatz' },
      { key: 'pencil', icon: Pencil, label: 'Stift', words: 'schreiben zeichnen' },
      { key: 'quote', icon: Quote, label: 'Zitat', words: 'rede text' },
      { key: 'type', icon: Type, label: 'Schrift', words: 'buchstaben rechtschreibung' },
      { key: 'languages', icon: Languages, label: 'Sprachen', words: 'englisch französisch' },
      { key: 'spell-check', icon: SpellCheck, label: 'Wortschatz', words: 'vokabeln vocabulary rechtschreibung' },
      { key: 'messages-square', icon: MessagesSquare, label: 'Diskussion', words: 'gespräch kommunikation' },
      { key: 'message-circle', icon: MessageCircle, label: 'Gespräch', words: 'dialog sprechen' },
      { key: 'mail', icon: Mail, label: 'Brief', words: 'e-mail schreiben' },
      { key: 'speech', icon: Speech, label: 'Rede', words: 'vortrag sprechen' },
      { key: 'presentation', icon: Presentation, label: 'Präsentation', words: 'referat vortrag' },
      { key: 'headphones', icon: Headphones, label: 'Hören', words: 'listening hörverstehen audio' },
      { key: 'mic', icon: Mic, label: 'Sprechen', words: 'speaking aussprache dialog' },
      { key: 'flag', icon: Flag, label: 'Landeskunde', words: 'land großbritannien usa kultur' },
    ],
  },
  {
    label: 'Alltag und Englisch-Themen',
    icons: [
      { key: 'home', icon: House, label: 'Zuhause', words: 'haus wohnen family familie home' },
      { key: 'sofa', icon: Sofa, label: 'Wohnzimmer', words: 'wohnen möbel' },
      { key: 'bed', icon: Bed, label: 'Schlafen', words: 'tagesablauf zimmer' },
      { key: 'school', icon: School, label: 'Schule', words: 'school klassenzimmer unterricht' },
      { key: 'backpack', icon: Backpack, label: 'Schulsachen', words: 'ranzen schule' },
      { key: 'shirt', icon: Shirt, label: 'Kleidung', words: 'clothes anziehen mode' },
      { key: 'glasses', icon: Glasses, label: 'Aussehen', words: 'brille beschreiben' },
      { key: 'dog', icon: Dog, label: 'Haustiere', words: 'pets tiere hund' },
      { key: 'cake', icon: Cake, label: 'Geburtstag', words: 'birthday feier party' },
      { key: 'party-popper', icon: PartyPopper, label: 'Feste', words: 'feiern festivals party' },
      { key: 'gift', icon: Gift, label: 'Geschenke', words: 'weihnachten christmas feiertage' },
      { key: 'candy-cane', icon: CandyCane, label: 'Weihnachten', words: 'christmas feiertage' },
      { key: 'ghost', icon: Ghost, label: 'Halloween', words: 'gruseln feiertage' },
      { key: 'utensils', icon: Utensils, label: 'Essen', words: 'food mahlzeit restaurant' },
      { key: 'pizza', icon: Pizza, label: 'Pizza', words: 'essen food' },
      { key: 'ice-cream-cone', icon: IceCreamCone, label: 'Eis', words: 'sommer essen' },
      { key: 'sandwich', icon: Sandwich, label: 'Pausenbrot', words: 'lunch essen' },
      { key: 'coffee', icon: Coffee, label: 'Frühstück', words: 'breakfast getränke' },
      { key: 'croissant', icon: Croissant, label: 'Bäckerei', words: 'frühstück einkaufen' },
      { key: 'shopping-cart', icon: ShoppingCart, label: 'Einkaufen', words: 'shopping geld laden' },
      { key: 'bus', icon: Bus, label: 'Unterwegs', words: 'schulweg verkehr stadt' },
      { key: 'bike', icon: Bike, label: 'Fahrrad', words: 'verkehr sport' },
      { key: 'tent', icon: Tent, label: 'Ferien', words: 'holidays urlaub camping reisen' },
      { key: 'tickets', icon: Tickets, label: 'Ausflug', words: 'tickets freizeit kino' },
      { key: 'gamepad-2', icon: Gamepad2, label: 'Freizeit', words: 'hobbys spiele free time' },
      { key: 'smartphone', icon: Smartphone, label: 'Handy', words: 'medien internet social media' },
      { key: 'tv', icon: Tv, label: 'Fernsehen', words: 'medien serien' },
    ],
  },
  {
    label: 'Kunst, Musik und Sport',
    icons: [
      { key: 'palette', icon: Palette, label: 'Kunst', words: 'malen farbe' },
      { key: 'brush', icon: Brush, label: 'Malen', words: 'kunst pinsel' },
      { key: 'scissors', icon: Scissors, label: 'Basteln', words: 'schneiden kunst' },
      { key: 'camera', icon: Camera, label: 'Foto', words: 'bild medien' },
      { key: 'clapperboard', icon: Clapperboard, label: 'Film', words: 'video medien' },
      { key: 'film', icon: Film, label: 'Video', words: 'film medien' },
      { key: 'popcorn', icon: Popcorn, label: 'Kino', words: 'film freizeit' },
      { key: 'drama', icon: Drama, label: 'Theater', words: 'schauspiel' },
      { key: 'music', icon: Music, label: 'Musik', words: 'lied noten' },
      { key: 'mic-vocal', icon: MicVocal, label: 'Singen', words: 'chor lied' },
      { key: 'guitar', icon: Guitar, label: 'Gitarre', words: 'instrument musik' },
      { key: 'piano', icon: Piano, label: 'Klavier', words: 'instrument musik' },
      { key: 'drum', icon: Drum, label: 'Trommel', words: 'rhythmus musik' },
      { key: 'dumbbell', icon: Dumbbell, label: 'Sport', words: 'fitness training' },
      { key: 'volleyball', icon: Volleyball, label: 'Ballsport', words: 'volleyball spiel' },
      { key: 'goal', icon: Goal, label: 'Tor', words: 'fußball ziel' },
      { key: 'medal', icon: Medal, label: 'Medaille', words: 'wettkampf sieg' },
      { key: 'trophy', icon: Trophy, label: 'Wettbewerb', words: 'sieg sport' },
    ],
  },
  {
    label: 'Allgemein',
    icons: [
      { key: 'graduation-cap', icon: GraduationCap, label: 'Abschluss', words: 'prüfung schule' },
      { key: 'puzzle', icon: Puzzle, label: 'Rätsel', words: 'knobeln' },
      { key: 'target', icon: Target, label: 'Ziel', words: 'lernziel' },
      { key: 'sparkles', icon: Sparkles, label: 'Kreativität', words: 'ideen besonders' },
      { key: 'star', icon: Star, label: 'Stern', words: 'favorit bewertung' },
      { key: 'heart', icon: Heart, label: 'Gefühle', words: 'liebe freundschaft' },
      { key: 'smile', icon: Smile, label: 'Stimmung', words: 'gefühle freude' },
      { key: 'search', icon: Search, label: 'Recherche', words: 'suchen finden' },
      { key: 'list-checks', icon: ListChecks, label: 'Checkliste', words: 'aufgaben liste' },
      { key: 'clipboard-list', icon: ClipboardList, label: 'Projekt', words: 'organisation planung' },
      { key: 'key', icon: Key, label: 'Schlüssel', words: 'lösung zugang' },
      { key: 'lock', icon: Lock, label: 'Datenschutz', words: 'privat sicherheit' },
      { key: 'shield-check', icon: ShieldCheck, label: 'Sicherheit', words: 'schutz internet' },
      { key: 'siren', icon: Siren, label: 'Notfall', words: 'polizei feuerwehr' },
      { key: 'briefcase-medical', icon: BriefcaseMedical, label: 'Erste Hilfe', words: 'notfall gesundheit' },
      { key: 'clock', icon: Clock, label: 'Uhr', words: 'zeit' },
      { key: 'alarm-clock', icon: AlarmClock, label: 'Wecker', words: 'zeit tagesablauf' },
      { key: 'calendar', icon: Calendar, label: 'Kalender', words: 'termin jahr' },
    ],
  },
];

export const TOPIC_ICONS: TopicIcon[] = TOPIC_GROUPS.flatMap((g) => g.icons);

const byKey = new Map(TOPIC_ICONS.map((t) => [t.key, t]));

export const isTopicIcon = (key: unknown): key is string => typeof key === 'string' && byKey.has(key);

export const topicIcon = (key: string): LucideIcon => (byKey.get(key) ?? byKey.get(DEFAULT_TOPIC_ICON)!).icon;

export function searchTopicIcons(query: string): TopicIcon[] {
  const q = query.trim().toLowerCase();
  if (!q) return TOPIC_ICONS;
  return TOPIC_ICONS.filter((t) => `${t.label} ${t.words ?? ''}`.toLowerCase().includes(q));
}
