// Topic icons for the header band (Kopfband): one icon per overarching topic, the same on every page.
// A curated set, so the bundle does not carry all of Lucide. Keys are Lucide's kebab-case names.
import {
  Anchor,
  Apple,
  Atom,
  Bike,
  Bird,
  BookOpen,
  Brain,
  Briefcase,
  Bug,
  Building2,
  Calculator,
  Calendar,
  Camera,
  Castle,
  ChartColumn,
  ChartPie,
  Church,
  Clapperboard,
  Clock,
  CloudRain,
  CloudSunRain,
  Code,
  Coins,
  Compass,
  Crown,
  Dna,
  Drama,
  Droplets,
  Dumbbell,
  Earth,
  Factory,
  Fish,
  Flame,
  FlaskConical,
  Flower2,
  Globe,
  GraduationCap,
  Handshake,
  HeartPulse,
  Hourglass,
  Landmark,
  Languages,
  Laptop,
  Leaf,
  Lightbulb,
  Magnet,
  Map as MapIcon,
  MapPin,
  MessagesSquare,
  Microscope,
  Moon,
  Mountain,
  Music,
  Newspaper,
  Palette,
  PawPrint,
  PenLine,
  Pickaxe,
  Plane,
  Puzzle,
  Recycle,
  Rocket,
  Ruler,
  Salad,
  Scale,
  Scroll,
  Shapes,
  Ship,
  Sigma,
  Snowflake,
  Sprout,
  Stethoscope,
  Sun,
  Sword,
  Target,
  Telescope,
  ThermometerSun,
  Tractor,
  Train,
  TreePine,
  Trophy,
  Users,
  Vote,
  Waves,
  Wheat,
  Wind,
  Zap,
  type LucideIcon,
} from 'lucide-react';

export interface TopicIcon {
  key: string;
  icon: LucideIcon;
  /** German name, shown as tooltip and matched by the search field. */
  label: string;
  /** Extra German search words. */
  words?: string;
}

export const DEFAULT_TOPIC_ICON = 'thermometer-sun';

export const TOPIC_ICONS: TopicIcon[] = [
  // Klima, Wetter, Erde
  { key: 'thermometer-sun', icon: ThermometerSun, label: 'Klima', words: 'temperatur treibhaus wärme' },
  { key: 'sun', icon: Sun, label: 'Sonne', words: 'energie licht' },
  { key: 'cloud-sun-rain', icon: CloudSunRain, label: 'Wetter' },
  { key: 'cloud-rain', icon: CloudRain, label: 'Niederschlag', words: 'regen wasserkreislauf' },
  { key: 'wind', icon: Wind, label: 'Wind', words: 'luft atmosphäre' },
  { key: 'snowflake', icon: Snowflake, label: 'Eis', words: 'schnee kälte gletscher polar' },
  { key: 'earth', icon: Earth, label: 'Erde', words: 'planet welt' },
  { key: 'globe', icon: Globe, label: 'Globus', words: 'welt länder' },
  { key: 'map', icon: MapIcon, label: 'Karte', words: 'atlas geographie' },
  { key: 'compass', icon: Compass, label: 'Kompass', words: 'orientierung himmelsrichtung' },
  { key: 'map-pin', icon: MapPin, label: 'Ort', words: 'lage standort' },
  { key: 'mountain', icon: Mountain, label: 'Gebirge', words: 'berg alpen relief vulkan' },
  { key: 'waves', icon: Waves, label: 'Meer', words: 'ozean küste wasser' },
  { key: 'droplets', icon: Droplets, label: 'Wasser', words: 'fluss trinkwasser' },
  { key: 'pickaxe', icon: Pickaxe, label: 'Rohstoffe', words: 'bergbau gestein' },
  // Natur und Leben
  { key: 'leaf', icon: Leaf, label: 'Pflanzen', words: 'biologie blatt' },
  { key: 'sprout', icon: Sprout, label: 'Wachstum', words: 'keimung samen' },
  { key: 'tree-pine', icon: TreePine, label: 'Wald', words: 'baum ökosystem' },
  { key: 'flower-2', icon: Flower2, label: 'Blüte', words: 'blume bestäubung' },
  { key: 'bug', icon: Bug, label: 'Insekten', words: 'käfer tiere' },
  { key: 'fish', icon: Fish, label: 'Fische', words: 'tiere wasser' },
  { key: 'bird', icon: Bird, label: 'Vögel', words: 'tiere' },
  { key: 'paw-print', icon: PawPrint, label: 'Tiere', words: 'säugetiere zoologie' },
  { key: 'dna', icon: Dna, label: 'Genetik', words: 'vererbung zelle' },
  { key: 'microscope', icon: Microscope, label: 'Mikroskop', words: 'zelle untersuchen' },
  { key: 'heart-pulse', icon: HeartPulse, label: 'Körper', words: 'herz kreislauf gesundheit' },
  { key: 'brain', icon: Brain, label: 'Gehirn', words: 'nerven lernen' },
  { key: 'stethoscope', icon: Stethoscope, label: 'Gesundheit', words: 'medizin krankheit' },
  { key: 'apple', icon: Apple, label: 'Ernährung', words: 'essen obst' },
  { key: 'salad', icon: Salad, label: 'Lebensmittel', words: 'essen kochen' },
  { key: 'wheat', icon: Wheat, label: 'Landwirtschaft', words: 'getreide ernte' },
  { key: 'recycle', icon: Recycle, label: 'Umwelt', words: 'nachhaltigkeit müll recycling' },
  // Physik, Chemie, Technik
  { key: 'atom', icon: Atom, label: 'Physik', words: 'teilchen' },
  { key: 'flask-conical', icon: FlaskConical, label: 'Chemie', words: 'versuch labor' },
  { key: 'magnet', icon: Magnet, label: 'Magnetismus' },
  { key: 'zap', icon: Zap, label: 'Elektrizität', words: 'strom energie' },
  { key: 'flame', icon: Flame, label: 'Feuer', words: 'verbrennung wärme' },
  { key: 'lightbulb', icon: Lightbulb, label: 'Idee', words: 'licht erfindung' },
  { key: 'rocket', icon: Rocket, label: 'Raumfahrt', words: 'weltall' },
  { key: 'telescope', icon: Telescope, label: 'Astronomie', words: 'sterne weltall' },
  { key: 'moon', icon: Moon, label: 'Mond', words: 'nacht weltall' },
  { key: 'laptop', icon: Laptop, label: 'Computer', words: 'informatik medien' },
  { key: 'code', icon: Code, label: 'Programmieren', words: 'informatik' },
  { key: 'factory', icon: Factory, label: 'Industrie', words: 'fabrik wirtschaft' },
  { key: 'tractor', icon: Tractor, label: 'Traktor', words: 'landwirtschaft' },
  { key: 'train', icon: Train, label: 'Verkehr', words: 'bahn mobilität' },
  { key: 'ship', icon: Ship, label: 'Handel', words: 'schiff hafen' },
  { key: 'plane', icon: Plane, label: 'Reisen', words: 'flugzeug tourismus' },
  { key: 'anchor', icon: Anchor, label: 'Hafen', words: 'seefahrt' },
  // Mathe
  { key: 'calculator', icon: Calculator, label: 'Rechnen', words: 'mathe' },
  { key: 'sigma', icon: Sigma, label: 'Mathematik', words: 'summe formel' },
  { key: 'ruler', icon: Ruler, label: 'Messen', words: 'geometrie länge' },
  { key: 'shapes', icon: Shapes, label: 'Geometrie', words: 'formen körper' },
  { key: 'chart-column', icon: ChartColumn, label: 'Diagramm', words: 'statistik daten' },
  { key: 'chart-pie', icon: ChartPie, label: 'Anteile', words: 'prozent bruch statistik' },
  // Gesellschaft und Geschichte
  { key: 'landmark', icon: Landmark, label: 'Staat', words: 'politik demokratie antike' },
  { key: 'vote', icon: Vote, label: 'Wahlen', words: 'politik demokratie' },
  { key: 'scale', icon: Scale, label: 'Recht', words: 'gerechtigkeit gesetz' },
  { key: 'users', icon: Users, label: 'Gesellschaft', words: 'gemeinschaft gruppe' },
  { key: 'handshake', icon: Handshake, label: 'Zusammenarbeit', words: 'frieden vertrag' },
  { key: 'coins', icon: Coins, label: 'Wirtschaft', words: 'geld finanzen' },
  { key: 'briefcase', icon: Briefcase, label: 'Beruf', words: 'arbeit berufsorientierung' },
  { key: 'building-2', icon: Building2, label: 'Stadt', words: 'urbanisierung' },
  { key: 'hourglass', icon: Hourglass, label: 'Zeit', words: 'geschichte epoche' },
  { key: 'scroll', icon: Scroll, label: 'Quellen', words: 'geschichte urkunde' },
  { key: 'castle', icon: Castle, label: 'Mittelalter', words: 'burg geschichte' },
  { key: 'crown', icon: Crown, label: 'Herrschaft', words: 'könig absolutismus' },
  { key: 'sword', icon: Sword, label: 'Konflikt', words: 'krieg geschichte' },
  { key: 'church', icon: Church, label: 'Religion', words: 'glaube ethik kirche' },
  { key: 'newspaper', icon: Newspaper, label: 'Medien', words: 'zeitung nachrichten' },
  // Sprache, Kunst, Musik, Sport
  { key: 'book-open', icon: BookOpen, label: 'Lesen', words: 'deutsch literatur buch' },
  { key: 'pen-line', icon: PenLine, label: 'Schreiben', words: 'deutsch aufsatz' },
  { key: 'languages', icon: Languages, label: 'Sprachen', words: 'englisch französisch' },
  { key: 'messages-square', icon: MessagesSquare, label: 'Diskussion', words: 'gespräch kommunikation' },
  { key: 'palette', icon: Palette, label: 'Kunst', words: 'malen farbe' },
  { key: 'camera', icon: Camera, label: 'Foto', words: 'bild medien' },
  { key: 'clapperboard', icon: Clapperboard, label: 'Film', words: 'video medien' },
  { key: 'drama', icon: Drama, label: 'Theater', words: 'schauspiel' },
  { key: 'music', icon: Music, label: 'Musik', words: 'lied noten' },
  { key: 'dumbbell', icon: Dumbbell, label: 'Sport', words: 'fitness training' },
  { key: 'bike', icon: Bike, label: 'Fahrrad', words: 'verkehr sport' },
  { key: 'trophy', icon: Trophy, label: 'Wettbewerb', words: 'sieg sport' },
  // Allgemein
  { key: 'graduation-cap', icon: GraduationCap, label: 'Abschluss', words: 'prüfung schule' },
  { key: 'puzzle', icon: Puzzle, label: 'Rätsel', words: 'knobeln' },
  { key: 'target', icon: Target, label: 'Ziel', words: 'lernziel' },
  { key: 'clock', icon: Clock, label: 'Uhr', words: 'zeit' },
  { key: 'calendar', icon: Calendar, label: 'Kalender', words: 'termin jahr' },
];

const byKey = new Map(TOPIC_ICONS.map((t) => [t.key, t]));

export const isTopicIcon = (key: unknown): key is string => typeof key === 'string' && byKey.has(key);

export const topicIcon = (key: string): LucideIcon => (byKey.get(key) ?? byKey.get(DEFAULT_TOPIC_ICON)!).icon;

export function searchTopicIcons(query: string): TopicIcon[] {
  const q = query.trim().toLowerCase();
  if (!q) return TOPIC_ICONS;
  return TOPIC_ICONS.filter((t) => `${t.label} ${t.words ?? ''}`.toLowerCase().includes(q));
}
